server:
  port: 9096
#配置数据源
spring:
  datasource:
    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    #数据源1
    driver-class-name: com.mysql.cj.jdbc.Driver
    #基本属性
    url: jdbc:mysql://127.0.0.1:3306/pay_db?serverTimezone=GMT%2B8&nullCatalogMeansCurrent=true
    username: root
    password: ls123
    #2.0以后开启这个 initialization-mode 才会自动执行sql脚本
    initialization-mode: always
    #配置初始化大小/最小/最大
    initial-size: 10
    min-idle: 10
    max-active: 100
    #获取连接等待超时时间
    max-wait: 30000
    #间隔多久进行一次检测，检测需要关闭的空闲连接
    time-between-eviction-runs-millis: 60000
    #一个连接在池中最小生存的时间
    min-evictable-idle-time-millis: 300000
    validation-query: SELECT 'x'
    test-while-idle: true
    test-on-borrow: false
    test-on-return: false
    #打开PSCache，并指定每个连接上PSCache的大小。oracle设为true，mysql设为false。分库分表较多推荐设置为false
    pool-prepared-statements: false
    max-pool-prepared-statement-per-connection-size: 20
    # 合并多个DruidDataSource的监控数据
    #use-global-data-source-stat: true
  main:
    allow-bean-definition-overriding: true
mybatis-plus:
  map-underscore-to-camel-case: true
  mapper-locations: classpath:mappers/*.xml
  type-aliases-package: com.ls.pay.po
logging:
  level:
    com.ls.pay.dao: debug